version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - webnet

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./app:/var/www/html
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

volumes:
  mariadb_data:

networks:
  webnet:
