services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - ncp
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u ${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 10s
      retries: 10
      timeout: 10s

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - ncp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/wp-admin"]
      interval: 10s
      retries: 10
      timeout: 10s

  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - ncp

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/arahmoun/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/arahmoun/data/wordpress
      o: bind

networks:
  ncp:
